import{a as q,S as M,i}from"./assets/vendor-C3hA4BqS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="34651867-a9ff37d4e5e76304c6c99ac31",B="https://pixabay.com/api/";async function h(o,t=1){const s={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(B,{params:s})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),$=new M(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r}</p>
          <p class="info-item"><b>Views:</b> ${n}</p>
          <p class="info-item"><b>Comments:</b> ${S}</p>
          <p class="info-item"><b>Downloads:</b> ${v}</p>
        </div>
      </a>
    </li>`).join("");g.insertAdjacentHTML("beforeend",t),$.refresh()}function x(){g.innerHTML=""}function b(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}function w(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const m=document.querySelector(".form"),E=document.querySelector(".load-more");let l="",c=1,f=0;const O=15;d();m.addEventListener("submit",H);E.addEventListener("click",A);async function H(o){if(o.preventDefault(),l=m.elements["search-text"]?m.elements["search-text"].value.trim():"",l===""){i.warning({message:"Please enter a search query!"});return}c=1,x(),d(),b();try{const t=await h(l,c);if(f=t.totalHits,t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}L(t.hits),f>15&&w()}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{u()}}async function A(){c+=1,d(),b();try{const o=await h(l,c);L(o.hits),D();const t=Math.ceil(f/O);c>=t?(d(),i.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch{i.error({message:"Error loading more images!"})}finally{u()}}function D(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
